[package]
name = "untitled1"
version = "0.1.0"
authors = ["tuyen <vat1906@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio-cdev = "0.2"
